#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	mkd="mkdir -pv" \
	yt="youtube-dl --add-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner" \
	connect="nmtui" \
	kali="docker run -t -v ~/docker-images-volumes/kali:/root/host -i kalilinux/kali-rolling /bin/bash" \
	cvim="nvim -u NONE" \
	svim="nvim /dev/null" \
	dsize="du --human-readable" \
	notif-toggle="dunstctl set-paused toggle"

# Colorize commands when possible.
alias \
	exa="exa --header" \
	ls="exa --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi"

# ls="ls -hN --color=auto --group-directories-first" \
# These common commands are just too long! Abbreviate them.
alias \
	gfdisk="cfdisk" \
	cls="clear" \
	ka="killall" \
	g="git" \
	trem="transmission-remote" \
	YT="youtube-viewer" \
	f="$FILE" \
	e="$EDITOR" \
	p="sudo pacman" \
	ll="ls -al" \
	yay="yay --answerclean All --answerdiff None" \
	bluetooth="blueman-applet"
alias \
	magit="nvim -c MagitOnly" \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/zshnameddirrc" \
	tmux="tmux -f ${XDG_CONFIG_HOME:-$HOME/.config}/tmux/tmux.conf" \
	android="aft-mtp-cli"

