Threshold = 23
DisplayMonitorSources = false
EnableUpdates = true
GuiltTripped = true
FilterInput = true
FilterOutput = false
LastUsedInput = "alsa_input.pci-0000_00_1f.3.analog-stereo"
LastUsedOutput = ""
